# Copyright 2024 Sara Lago
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

{
    "name": "Roomdoo SAAS",
    "summary": "Roomdoo SaaS preconfig",
    "version": "14.0.1.1",
    "author": "Commit [Sun], Odoo Community Association (OCA)",
    "website": "https://github.com/OCA/pms",
    "license": "AGPL-3",
    "depends": [
        "base",
        "pms_api_rest",
        "connector_pms_wubook",
        "pms_l10n_es",
        "web_responsive",
        "payment_redsys",
        "l10n_es_partner",
        "base_location_geonames_import",
        "cash_daily_report",
        "kellys_daily_report",
        "l10n_es_toponyms",
        "mass_editing",
        "account_invoice_constraint_chronology",
        "web_advanced_search",
        "multi_step_wizard",
    ],
    "data": [
        "wizards/property_wizard_views.xml",
        "data/roomdoo_account_journal_data.xml",
        "data/roomdoo_amenity_type_data.xml",
        "data/roomdoo_amenity_data.xml",
        "data/roomdoo_room_type_class_data.xml",
        "data/roomdoo_availability_plan_data.xml",
        "data/roomdoo_pricelist_data.xml",
        "data/roomdoo_backend_type_data.xml",
        "data/roomdoo_backend_data.xml",
        "data/roomdoo_categories_data.xml",
        "data/roomdoo_product_template_data.xml",
        "data/roomdoo_company_data.xml",
        "data/roomdoo_otas_data.xml",
        "data/roomdoo_property_data.xml",
        "data/roomdoo_room_type_data.xml",
        "data/roomdoo_settings_data.xml",
        "data/roomdoo_tax_data.xml",
        "data/roomdoo_user_data.xml",
        # "templates/cancelation_mail_template.xml",
        # "templates/confirmation_mail_template.xml",
    ],
    "auto_install": False,
    "installable": True,
    # "post_init_hook": "hooks",
}
